spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviestore
    username: postgres
    password: qwertz
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

